"""empty message

Revision ID: 842d37835aa6
Revises: ef54418a631d
Create Date: 2025-08-29 15:39:36.621423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842d37835aa6'
down_revision = 'ef54418a631d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=140),
               nullable=True)
        batch_op.drop_column('last_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_time', sa.DATETIME(), nullable=True))
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
