"""add post  langage table

Revision ID: d62fb4838c95
Revises: 1c56172aafe4
Create Date: 2025-09-02 16:38:23.981372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62fb4838c95'
down_revision = '1c56172aafe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang_post', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('lang_post')

    # ### end Alembic commands ###
