"""empty message

Revision ID: ef54418a631d
Revises: 4711310fa23a
Create Date: 2025-08-29 15:19:41.100911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef54418a631d'
down_revision = '4711310fa23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('last_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_time')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
